<a href="https://colab.research.google.com/github/nferrucho/Diplomado_Ciencia_Datos/blob/main/Tarea2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
alfabeto = 'abced'
listAlfa = []
for i in alfabeto:
  listAlfa.append(i)
print (listAlfa)


['a', 'b', 'c', 'e', 'd']


In [ ]:
len(listAlfa)

5

Asi hemos pasado un texto a una lista con **append**



In [ ]:
listB = listAlfa.copy()
print (listB)

['a', 'b', 'c', 'e', 'd']


In [ ]:
print(listB.index('b'))

1


In [ ]:
tupla = tuple(listB)
print(tupla)

('a', 'b', 'c', 'e', 'd')


In [ ]:
print(tupla[:3])

('a', 'b', 'c')


In [ ]:
print (tupla[1:])

('b', 'c', 'e', 'd')


In [ ]:
print (tupla[::2])

('a', 'c', 'd')


In [ ]:
print(listB[0])

a


In [ ]:
listC = list('esta es una cadena')
print (listC)
listC = tuple(listC)
print (listC)
print (type(listC))

['e', 's', 't', 'a', ' ', 'e', 's', ' ', 'u', 'n', 'a', ' ', 'c', 'a', 'd', 'e', 'n', 'a']
('e', 's', 't', 'a', ' ', 'e', 's', ' ', 'u', 'n', 'a', ' ', 'c', 'a', 'd', 'e', 'n', 'a')
<class 'tuple'>


In [ ]:
dict1 ={}
dict1 = {'colores': ['amarillo', 'azul','verde'],
         'animales':'gato',
         'valoes': {10,12,30},
         }

In [ ]:
!pip install numpy
import numpy as np


In [ ]:
a = np.array([13, 12, 120])
print(type(a))
print (a)

<class 'numpy.ndarray'>
[ 13  12 120]


In [ ]:
b = np.array([[13, 12, 120], [5,6,7]])
print (b)

[[ 13  12 120]
 [  5   6   7]]


In [ ]:
from numpy.random import default_rng


In [ ]:
print(b[1])

[5 6 7]


In [ ]:
semilla = 567890
rng = default_rng(semilla)


In [ ]:
import pandas as pd

In [ ]:
ciudades= pd.read_excel("")

In [ ]:
class Usuario:
  pass

print (Usuario)

<class '__main__.Usuario'>


In [ ]:
user1 = Usuario()
user1.nombre = 'nelson'
print (user1.nombre)
user1.nombre

nelson


'nelson'

In [ ]:
user2 = Usuario()
user2.edad = 52
user2.edad

52

In [ ]:
class User:
  def __init__(self, nombre, edad):
    self.nombre = nombre
    self.edad = edad
    self.llamado = 0

  def imprime_edad(self, edad):
    cadena  = print("la edad es", self.edad)
    return(cadena)

  def __call__(self):
    self.llamado +=1
    return(self.llamado)

u3 = User('nelson', 52)
print (u3.nombre)
print (u3.edad)
u3.nombre

print(u3.imprime_edad(52))
print(u3())
print(u3())
#print(u3.imprime_edad)


nelson
52
la edad es 52
None
1
2


In [ ]:
help(User)

Help on class User in module __main__:

class User(builtins.object)
 |  User(nombre, edad)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, nombre, edad)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)

